// .github/workflows/axe.yaml 
name: ax 
on: 
  push: 
    branches: [master] 
  pull_request: 
    branches: [master] 
jobs: 
  axe: 
    runs-on: ubuntu-últimas 
    etapas: 
      - uses: actions/checkout@v2 
      - nome: Use Node.js 12.x 
        usa: actions/setup-node@v1 
        com: 
          node-version: 12.x 
      - execute: npm ci 
      - execute: npm run build --if-present 
      - execute: npm start & npx wait-on http://localhost:3000 
      - name: Run ax 
        run: | 
          npm install -g @axe-core/cli 
          ax http://localhost:3000 --exit